@startuml

class Player {
    String name
    Cards[] playerPrgrammingCards
    Cards[] playerDamageCards
    int checkpointTokens
    int energyCubes
    Vector2 location
}

class Board {
    BoardTile startTile
}
Board *- BoardTile
Board "1" -- "2..4" Player

interface BoardTile { }

class RebootToken implements BoardTile { }
class PriorityAntenna implements BoardTile { }
class Checkpoint implements BoardTile {
    int number
}
class ConveyorBelt implements BoardTile {
    int spacesToMove
    Direction direction (N/S/E/W)
}
class PushPanel {
    int register1
    int register2
    Direction direction
}
BoardTile <|.up. PushPanel
class Gears implements BoardTile {
    bool clockwise
}
class BoardLaser implements BoardTile {
    int amount
    Direction direction
}
class Pit implements BoardTile {}
class EnergySpace implements BoardTile {
    int energyCubes
}
class Walls implements BoardTile {
    
}

class UpgradeShop { }
UpgradeShop o- UpgradeCard

interface ProgrammingCard { }
interface DamageCard implements ProgrammingCard { }
interface UpgradeCard { 
    boolean temporary
}

@enduml